/*
Fipe API

API de Consulta Tabela FIPE fornece preços médios de veículos no mercado nacional. Atualizada mensalmente com dados extraidos da tabela FIPE

API version: 2.0.0
Contact: deividfortuna@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fipe

import (
	"encoding/json"
)

// NamedCode struct for NamedCode
type NamedCode struct {
	Name *string `json:"name,omitempty"`
	Code *string `json:"code,omitempty"`
}

// NewNamedCode instantiates a new NamedCode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNamedCode() *NamedCode {
	this := NamedCode{}
	return &this
}

// NewNamedCodeWithDefaults instantiates a new NamedCode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNamedCodeWithDefaults() *NamedCode {
	this := NamedCode{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *NamedCode) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NamedCode) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *NamedCode) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *NamedCode) SetName(v string) {
	o.Name = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *NamedCode) GetCode() string {
	if o == nil || o.Code == nil {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NamedCode) GetCodeOk() (*string, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *NamedCode) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *NamedCode) SetCode(v string) {
	o.Code = &v
}

func (o NamedCode) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	return json.Marshal(toSerialize)
}

type NullableNamedCode struct {
	value *NamedCode
	isSet bool
}

func (v NullableNamedCode) Get() *NamedCode {
	return v.value
}

func (v *NullableNamedCode) Set(val *NamedCode) {
	v.value = val
	v.isSet = true
}

func (v NullableNamedCode) IsSet() bool {
	return v.isSet
}

func (v *NullableNamedCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNamedCode(val *NamedCode) *NullableNamedCode {
	return &NullableNamedCode{value: val, isSet: true}
}

func (v NullableNamedCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNamedCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


